name: customization_config_policy
description: The configuration policy component, namely, customization_config_policy, provides APIs for each service module to obtain the configuration directories at different levels or the configuration file paths.
upstream: https://gitee.com/openharmony/customization_config_policy
branches:
- name: master
  type: protected
- name: openEuler-22.03-LTS-Next
  type: protected
  create_from: master
- name: openEuler-22.03-LTS-SP2
  type: protected
  create_from: openEuler-22.03-LTS-Next
type: public
