name: rqt_reconfigure
description: The Robot Operating System(ROS) project, include rqt-reconfigure.
upstream: https://packages.ros.org/ros2/ubuntu/pool/main/r
branches:
- name: master
  type: protected
- name: humble
  type: protected
  create_from: master
type: public
