name: portal-application-license-monitor
description: portal-application-license-monitor provides a best practice for Donau Portal to interconnect with the FlexNet license management utility.
branches:
  - name: master
    type: protected
type: public